### ISSUE TITLE
Not supported on this computer. Windows 8

### ISSUE THREAD

**Issue by japborst** [googlearchive/ADBPlugin#11]
Hi,

When going to the [Chrome store](https://chrome.google.com/webstore/detail/adb/dpngiggdglpdnjdoaefidgiigpemgage), I see the message: "This application is not supported on this computer. Installation has been disabled." And indeed, installation is not possible.

I'm running Chrome Canary 30.0.1552.0 on a Windows 8.1 machine.

Any ideas?

Thanks!

**Comment by paulirish** [comment]
Windows 8.1, eh? :)

Thanks for the report. Does the legacy path of using ADB work for you? 
https://developers.google.com/chrome-developer-tools/docs/remote-debugging#remote-debugging-stable

**Comment by garthenweb** [comment]
Same problem here, but on Windows 8.0. The installation outside of the webstore was working fine for me.

**Comment by paulirish** [comment]
Very useful feedback. Thanks.

The crx via the /out folder in this repo is still available.

But we'll look into the win8 issues for the CWS (chrome web store) install.

**Comment by japborst** [comment]
@paulirish : 8.1 indeed so ;) 

I don't have the full SDK installed, as I used tools such as Edge Inspect before. I tried installing the .crx directly from the `/out` folder, which worked. Connecting my phone to USB, starting ADB, no device is listed and I just see the pages from my local machine.

Thanks for all the help.

**Comment by arthurevans** [comment]
@japborst

You've probably run through all this, but just in case, here are some basic debugging steps:

Is USB debugging enabled on the phone _and_ USB Web debugging enabled in Chrome for Android? 

Device won't show up unless Chrome is running on the device with USB debugging enabled in both places. Sometimes unplugging, replugging, and restarting chrome helps.

If running "adb devices" shows the device connected but it _doesn't_ show up in Chrome, the problem is in the Chrome for Android-ADB extension-DevTools chain. Verify that you're running the Beta version of Chrome for Android, that USB debugging is enabled in CfA, and try restarting CfA.

If the device doesn't show up in adb devices, it's an ADB problem. You may not have the correct windows USB driver for your system, ADB may be flaky, bad USB cable ... I've seen all of these. 
- USB drivers. See:
  
  http://developer.android.com/tools/extras/oem-usb.html
- Flaky ADB. Stop and start ADB from the extension menu, or run "adb kill-server" followed by "adb devices".

**Comment by japborst** [comment]
Thanks @arthurevans! I found that I had some troubles with the HTC drivers being installed incorrectly. Working perfectly now.

**Comment by paulirish** [comment]
@japborst it's still not installable from the webstore right? but you've installed from the crx in here and you're up and running now.

@arthurevans Thanks!!

**Comment by japborst** [comment]
@paulirish Indeed so!

**Comment by paulirish** [comment]
i augmented the readme to account for this. thanks all!

**Comment by ChrisMcKee** [comment]
Still not working from the web store

**Comment by paulirish** [comment]
I recommend everyone use the raw USB debugging. 

In older versions you can find it in about:flags .. In newer versions, it's enabled by default.

With it you don't need this extension (or ADB) at all. Just plug in the phone and go.

**Comment by ChrisMcKee** [comment]
@paulirish nice, debugging porn.
