### ISSUE TITLE
Not working on Windows 7

### ISSUE THREAD

**Issue by garthenweb** [googlearchive/ADBPlugin#15]
After installation from webstore and plugin the device, Chrome crashes.
I restartet the browser and installed ADB again (it was removed from extensions).
Reinstallation went well, but then I recognized a hight CPU usage (about 50%). ADB was also not working, just the active state of the icon was shown.
Deactivation the plugin in extension manager was not possible without killing the process via taskmanager before.

OS: Windows 7
Device: Nexus 4
Browser: Chrome canary version 30.0.1553.3

**Comment by byron633** [comment]
I am seeing the same issue.

I have successfully used the ADB plugin to debug a Samsung galaxy tab 2 10.1 but since then the plugin has never worked. I see the active state in the icon once a device is detected but clicking it crashes chrome. Attempting to remove the plugin also crashes chrome.

Since installing the plugin I regularly see chrome crashing. Most often when closing the window it just freezes. Alternatively when closing the window it closes correctly but multiple processes are running and these must be manually stopped in task manager before I am able to open chrome again.

Chome Version 31.0.1650.63 m
Windows 7

**Comment by paulirish** [comment]
Please follow the updated directions for remote debugging. As of Chrome 32 there is functionality built in and the extension is no longer needed.

https://developers.google.com/chrome-developer-tools/docs/remote-debugging#remote-debugging
